global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "job-queue-api"
    static_configs:
      - targets: ["api:3000"]

  - job_name: "job-queue-worker"
    static_configs:
      - targets: ["worker:4000"]
